--------------------------------------------------------
--  File created - Thursday-June-22-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTRIBUTE
--------------------------------------------------------

  CREATE TABLE "NTG"."ATTRIBUTE" 
   (	"ID" NUMBER(19,2), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"MANDATORY" NUMBER(19,2), 
	"NAME" VARCHAR2(255 CHAR), 
	"SORT" NUMBER(19,2), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SERVICE_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ATTRIBUTE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."ATTRIBUTE_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"MANDATORY" NUMBER(19,2), 
	"NAME" VARCHAR2(255 CHAR), 
	"SORT" NUMBER(19,2), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SERVICE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ATTRIBUTE_VALUE
--------------------------------------------------------

  CREATE TABLE "NTG"."ATTRIBUTE_VALUE" 
   (	"ATTRIBUTE_ID" NUMBER(19,2), 
	"ORDER_ID" NUMBER(19,2), 
	"SERVICE_ID" NUMBER(19,2), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"VALUE" VARCHAR2(255 CHAR), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ATTRIBUTE_VALUE_LIST
--------------------------------------------------------

  CREATE TABLE "NTG"."ATTRIBUTE_VALUE_LIST" 
   (	"ATTRIBUTE_ID" NUMBER(19,2), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"VALUE" VARCHAR2(255 CHAR), 
	"SERVICEID" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ATTRIBUTE_VALUE_LIST_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."ATTRIBUTE_VALUE_LIST_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"VALUE" VARCHAR2(255 CHAR), 
	"ATTRIBUTE_ID" NUMBER(19,0), 
	"SERVICEID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ATTRIBUTE_VALUE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."ATTRIBUTE_VALUE_NTGL" 
   (	"ATTRIBUTE_ID" NUMBER(19,2), 
	"ORDER_ID" NUMBER(19,2), 
	"SERVICE_ID" NUMBER(19,2), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"VALUE" VARCHAR2(255 CHAR), 
	"ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANDWIDTH
--------------------------------------------------------

  CREATE TABLE "NTG"."BANDWIDTH" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"VALUE" NUMBER(10,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANDWIDTH_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."BANDWIDTH_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(20 CHAR), 
	"VALUE" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANCELATION_REASON
--------------------------------------------------------

  CREATE TABLE "NTG"."CANCELATION_REASON" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CANCELREASON" VARCHAR2(255 CHAR), 
	"ISCUSTOMERREQUEST" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANCELATION_REASON_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."CANCELATION_REASON_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CANCELREASON" VARCHAR2(255 CHAR), 
	"ISCUSTOMERREQUEST" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "NTG"."CATEGORY" 
   (	"ID" NUMBER(19,2), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SERVICE_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."CATEGORY_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SERVICE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPONENT
--------------------------------------------------------

  CREATE TABLE "NTG"."COMPONENT" 
   (	"ID" NUMBER(19,2), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"MRC" NUMBER(19,2), 
	"NAME" VARCHAR2(255 CHAR), 
	"NRC" NUMBER(19,2), 
	"CATEGORYID_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPONENT_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."COMPONENT_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"MRC" NUMBER(19,2), 
	"NAME" VARCHAR2(255 CHAR), 
	"NRC" NUMBER(19,2), 
	"CATEGORYID_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTRACTTERMS
--------------------------------------------------------

  CREATE TABLE "NTG"."CONTRACTTERMS" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CONTRACTTERM" VARCHAR2(255 CHAR), 
	"DEFAULTCONTRACT" NUMBER(19,2), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"ISWEBCONTENT" NUMBER(19,2), 
	"NUMBEROFMONTHS" NUMBER(19,2), 
	"RECID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTRACTTERMS_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."CONTRACTTERMS_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CONTRACTTERM" VARCHAR2(255 CHAR), 
	"DEFAULTCONTRACT" NUMBER(19,2), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"ISWEBCONTENT" NUMBER(19,2), 
	"NUMBEROFMONTHS" NUMBER(19,2), 
	"RECID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DISCOUNT_CATEGORY
--------------------------------------------------------

  CREATE TABLE "NTG"."DISCOUNT_CATEGORY" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DISCOUNT_CATEGORY_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."DISCOUNT_CATEGORY_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOWNLOAD_TYPE
--------------------------------------------------------

  CREATE TABLE "NTG"."DOWNLOAD_TYPE" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOWNLOAD_TYPE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."DOWNLOAD_TYPE_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEEDISCOUNT
--------------------------------------------------------

  CREATE TABLE "NTG"."EMPLOYEEDISCOUNT" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DISCOUNT_CATEGORY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEEDISCOUNT_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."EMPLOYEEDISCOUNT_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DISCOUNT_CATEGORY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HIBERNATE_SEQUENCES
--------------------------------------------------------

  CREATE TABLE "NTG"."HIBERNATE_SEQUENCES" 
   (	"SEQUENCE_NAME" VARCHAR2(255 CHAR), 
	"SEQUENCE_NEXT_HI_VALUE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ID_TABLE
--------------------------------------------------------

  CREATE TABLE "NTG"."ID_TABLE" 
   (	"PK" VARCHAR2(255 CHAR), 
	"VALUE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODIFYREASON
--------------------------------------------------------

  CREATE TABLE "NTG"."MODIFYREASON" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"MODIFYREASON" VARCHAR2(255 CHAR), 
	"RECID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODIFYREASON_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."MODIFYREASON_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"MODIFYREASON" VARCHAR2(255 CHAR), 
	"RECID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "NTG"."ORDERS" 
   (	"ID" NUMBER(19,2), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"PHONE" VARCHAR2(255 CHAR), 
	"QUANTITY" NUMBER(10,0), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"SERVICEID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERS_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."ORDERS_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"PHONE" VARCHAR2(255 CHAR), 
	"QUANTITY" NUMBER(10,0), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"SERVICEID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PC_DELIVERY_TYPE
--------------------------------------------------------

  CREATE TABLE "NTG"."PC_DELIVERY_TYPE" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PC_DELIVERY_TYPE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."PC_DELIVERY_TYPE_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRICE_BASIS
--------------------------------------------------------

  CREATE TABLE "NTG"."PRICE_BASIS" 
   (	"ID" NUMBER, 
	"DESCRIBTION" VARCHAR2(50 BYTE), 
	"NUMBEROFMONTHS" NUMBER(3,0), 
	"FREEDAYSONCE" NUMBER(4,0), 
	"FREEDAYSSERVICEBILL" NUMBER(4,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRICE_BASIS_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."PRICE_BASIS_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"COLUMN1" VARCHAR2(1 CHAR), 
	"DESCRIBTION" VARCHAR2(50 CHAR), 
	"FREEDAYSONCE" NUMBER(5,0), 
	"FREEDAYSSERVICEBILL" VARCHAR2(20 CHAR), 
	"NUMBEROFMONTHS" NUMBER(5,0), 
	"NAME" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVINFO
--------------------------------------------------------

  CREATE TABLE "NTG"."REVINFO" 
   (	"REV" NUMBER(10,0), 
	"REVTSTMP" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SELLING_TYPE
--------------------------------------------------------

  CREATE TABLE "NTG"."SELLING_TYPE" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"HIDE_IN_DROP_DOWN" NUMBER(19,2), 
	"TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SELLING_TYPE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."SELLING_TYPE_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"HIDE_IN_DROP_DOWN" NUMBER(19,2), 
	"TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICE" 
   (	"ID" NUMBER(19,2), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DATE_CREATED" TIMESTAMP (6), 
	"DELIVERY_DAYS" NUMBER(19,2), 
	"DELIVERY_FEES" NUMBER(19,2), 
	"ISACTIVE" NUMBER(19,2), 
	"NAME" VARCHAR2(255 CHAR), 
	"SUSPENSION_FEES" NUMBER(19,2), 
	"TERMINATION_FEES" NUMBER(19,2), 
	"TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICEMIGRATION
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICEMIGRATION" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"FROMSERVICEID" NUMBER(19,2), 
	"RECID" NUMBER(19,2), 
	"REQUESTID" NUMBER(19,2), 
	"SERVICEID" NUMBER(19,2), 
	"TOSERVICEID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICEMIGRATION_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICEMIGRATION_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"FROMSERVICEID" NUMBER(19,2), 
	"RECID" NUMBER(19,2), 
	"REQUESTID" NUMBER(19,2), 
	"SERVICEID" NUMBER(19,2), 
	"TOSERVICEID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICETYPE
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICETYPE" 
   (	"ID" NUMBER, 
	"SERVICE_TYPE" VARCHAR2(50 BYTE), 
	"DESCRIBTION" VARCHAR2(50 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICETYPE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICETYPE_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DESCRIBTION" VARCHAR2(50 CHAR), 
	"SERVICE_TYPE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE_BUNDLE
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICE_BUNDLE" 
   (	"COMP_ID" NUMBER(19,2), 
	"SERVICE_ID" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE_BUNDLE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICE_BUNDLE_NTGL" 
   (	"REV" NUMBER(10,0), 
	"COMP_ID" NUMBER(19,0), 
	"SERVICE_ID" NUMBER(19,0), 
	"REVTYPE" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE_CATEGORY
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICE_CATEGORY" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"BANDWIDTH_COVERAGE_APPLICABLE" NUMBER(19,2), 
	"FUP_APLLICABLE" NUMBER(19,2), 
	"NAME" VARCHAR2(255 CHAR), 
	"SERVICE_ACIVATION_GL_CODE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE_CATEGORY_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICE_CATEGORY_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"BANDWIDTH_COVERAGE_APPLICABLE" NUMBER(19,2), 
	"FUP_APLLICABLE" NUMBER(19,2), 
	"NAME" VARCHAR2(255 CHAR), 
	"SERVICE_ACIVATION_GL_CODE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."SERVICE_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"DATE_CREATED" TIMESTAMP (6), 
	"DELIVERY_DAYS" NUMBER(19,2), 
	"DELIVERY_FEES" NUMBER(19,2), 
	"ISACTIVE" NUMBER(19,2), 
	"NAME" VARCHAR2(255 CHAR), 
	"SUSPENSION_FEES" NUMBER(19,2), 
	"TERMINATION_FEES" NUMBER(19,2), 
	"TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "NTG"."TEST" 
   (	"NAME" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST2
--------------------------------------------------------

  CREATE TABLE "NTG"."TEST2" 
   (	"NAME" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST3
--------------------------------------------------------

  CREATE TABLE "NTG"."TEST3" 
   (	"NAME" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST4
--------------------------------------------------------

  CREATE TABLE "NTG"."TEST4" 
   (	"NAME" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERTABLE
--------------------------------------------------------

  CREATE TABLE "NTG"."USERTABLE" 
   (	"ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"AGE" NUMBER(19,2), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERTABLE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."USERTABLE_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"AGE" NUMBER(19,2), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_TABLE
--------------------------------------------------------

  CREATE TABLE "NTG"."USER_TABLE" 
   (	"ID" NUMBER(19,2), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"COLUMN1" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_TABLE_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."USER_TABLE_NTGL" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"COLUMN1" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VO_SUBSCRIBER
--------------------------------------------------------

  CREATE TABLE "NTG"."VO_SUBSCRIBER" 
   (	"REC_ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"ALLOWED_DEVICES" NUMBER(10,0), 
	"IMPI" VARCHAR2(255 CHAR), 
	"IMPU" VARCHAR2(255 CHAR), 
	"IMSI_DEFAULT" VARCHAR2(255 CHAR), 
	"MSISDN" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"SMSC" VARCHAR2(255 CHAR), 
	"USER_NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VO_SUBSCRIBER_NTGL
--------------------------------------------------------

  CREATE TABLE "NTG"."VO_SUBSCRIBER_NTGL" 
   (	"REC_ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CREATED_AT" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(10,0), 
	"UPDATED_AT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"ALLOWED_DEVICES" NUMBER(10,0), 
	"IMPI" VARCHAR2(255 CHAR), 
	"IMPU" VARCHAR2(255 CHAR), 
	"IMSI_DEFAULT" VARCHAR2(255 CHAR), 
	"MSISDN" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"SMSC" VARCHAR2(255 CHAR), 
	"USER_NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table schema_version
--------------------------------------------------------

  CREATE TABLE "NTG"."schema_version" 
   (	"version_rank" NUMBER(*,0), 
	"installed_rank" NUMBER(*,0), 
	"version" VARCHAR2(50 BYTE), 
	"description" VARCHAR2(200 BYTE), 
	"type" VARCHAR2(20 BYTE), 
	"script" VARCHAR2(1000 BYTE), 
	"checksum" NUMBER(*,0), 
	"installed_by" VARCHAR2(100 BYTE), 
	"installed_on" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"execution_time" NUMBER(*,0), 
	"success" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ATTRIBUTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NTG"."ATTRIBUTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ATTRIBUTE_VALUE_LIST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NTG"."ATTRIBUTE_VALUE_LIST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NTG"."CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "NTG"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 381 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_VO_SUBSCRIBER
--------------------------------------------------------

   CREATE SEQUENCE  "NTG"."SEQ_VO_SUBSCRIBER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERTABLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NTG"."USERTABLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTG"."TABLE1_PK" ON "NTG"."DISCOUNT_CATEGORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index schema_version_vr_idx
--------------------------------------------------------

  CREATE INDEX "NTG"."schema_version_vr_idx" ON "NTG"."schema_version" ("version_rank") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERVICETYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTG"."SERVICETYPE_PK" ON "NTG"."SERVICETYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ATTRIBUTE_VALUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTG"."ATTRIBUTE_VALUE_PK" ON "NTG"."ATTRIBUTE_VALUE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011621
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTG"."SYS_C0011621" ON "NTG"."ATTRIBUTE_VALUE_LIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRICE_BASIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTG"."PRICE_BASIS_PK" ON "NTG"."PRICE_BASIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BANDWIDTH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTG"."BANDWIDTH_PK" ON "NTG"."BANDWIDTH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index schema_version_s_idx
--------------------------------------------------------

  CREATE INDEX "NTG"."schema_version_s_idx" ON "NTG"."schema_version" ("success") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index schema_version_ir_idx
--------------------------------------------------------

  CREATE INDEX "NTG"."schema_version_ir_idx" ON "NTG"."schema_version" ("installed_rank") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index schema_version_pk
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTG"."schema_version_pk" ON "NTG"."schema_version" ("version") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REVINFO
--------------------------------------------------------

  ALTER TABLE "NTG"."REVINFO" ADD PRIMARY KEY ("REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."REVINFO" MODIFY ("REV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODIFYREASON
--------------------------------------------------------

  ALTER TABLE "NTG"."MODIFYREASON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."MODIFYREASON" MODIFY ("RECID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."MODIFYREASON" MODIFY ("MODIFYREASON" NOT NULL ENABLE);
  ALTER TABLE "NTG"."MODIFYREASON" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRICE_BASIS
--------------------------------------------------------

  ALTER TABLE "NTG"."PRICE_BASIS" ADD CONSTRAINT "PRICE_BASIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."PRICE_BASIS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VO_SUBSCRIBER_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."VO_SUBSCRIBER_NTGL" ADD PRIMARY KEY ("REC_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."VO_SUBSCRIBER_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."VO_SUBSCRIBER_NTGL" MODIFY ("REC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANDWIDTH
--------------------------------------------------------

  ALTER TABLE "NTG"."BANDWIDTH" ADD CONSTRAINT "BANDWIDTH_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."BANDWIDTH" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "NTG"."TEST" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."TEST" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTRACTTERMS_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."CONTRACTTERMS_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."CONTRACTTERMS_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."CONTRACTTERMS_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODIFYREASON_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."MODIFYREASON_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."MODIFYREASON_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."MODIFYREASON_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANCELATION_REASON
--------------------------------------------------------

  ALTER TABLE "NTG"."CANCELATION_REASON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."CANCELATION_REASON" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table schema_version
--------------------------------------------------------

  ALTER TABLE "NTG"."schema_version" ADD CONSTRAINT "schema_version_pk" PRIMARY KEY ("version")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."schema_version" MODIFY ("success" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("execution_time" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("installed_on" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("installed_by" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("script" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("type" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("description" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("version" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("installed_rank" NOT NULL ENABLE);
  ALTER TABLE "NTG"."schema_version" MODIFY ("version_rank" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERTABLE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."USERTABLE_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."USERTABLE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."USERTABLE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VO_SUBSCRIBER
--------------------------------------------------------

  ALTER TABLE "NTG"."VO_SUBSCRIBER" ADD PRIMARY KEY ("REC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."VO_SUBSCRIBER" MODIFY ("REC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOWNLOAD_TYPE
--------------------------------------------------------

  ALTER TABLE "NTG"."DOWNLOAD_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."DOWNLOAD_TYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_CATEGORY_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_CATEGORY_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICE_CATEGORY_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICE_CATEGORY_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SELLING_TYPE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SELLING_TYPE_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SELLING_TYPE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SELLING_TYPE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST4
--------------------------------------------------------

  ALTER TABLE "NTG"."TEST4" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."TEST4" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERTABLE
--------------------------------------------------------

  ALTER TABLE "NTG"."USERTABLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."USERTABLE" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "NTG"."USERTABLE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "NTG"."USERTABLE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "NTG"."USERTABLE" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "NTG"."USERTABLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST2
--------------------------------------------------------

  ALTER TABLE "NTG"."TEST2" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."TEST2" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_BUNDLE
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_BUNDLE" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICE_BUNDLE" MODIFY ("COMP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PC_DELIVERY_TYPE
--------------------------------------------------------

  ALTER TABLE "NTG"."PC_DELIVERY_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."PC_DELIVERY_TYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTRIBUTE
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."ATTRIBUTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISCOUNT_CATEGORY
--------------------------------------------------------

  ALTER TABLE "NTG"."DISCOUNT_CATEGORY" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."DISCOUNT_CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANDWIDTH_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."BANDWIDTH_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."BANDWIDTH_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."BANDWIDTH_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."CATEGORY_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."CATEGORY_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."CATEGORY_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "NTG"."CATEGORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "NTG"."ORDERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."ORDERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ORDERS" MODIFY ("SERVICEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_TABLE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."USER_TABLE_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."USER_TABLE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."USER_TABLE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICEMIGRATION
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICEMIGRATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICEMIGRATION" MODIFY ("TOSERVICEID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICEMIGRATION" MODIFY ("SERVICEID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICEMIGRATION" MODIFY ("REQUESTID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICEMIGRATION" MODIFY ("RECID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICEMIGRATION" MODIFY ("FROMSERVICEID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICEMIGRATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTRACTTERMS
--------------------------------------------------------

  ALTER TABLE "NTG"."CONTRACTTERMS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."CONTRACTTERMS" MODIFY ("RECID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."CONTRACTTERMS" MODIFY ("NUMBEROFMONTHS" NOT NULL ENABLE);
  ALTER TABLE "NTG"."CONTRACTTERMS" MODIFY ("CONTRACTTERM" NOT NULL ENABLE);
  ALTER TABLE "NTG"."CONTRACTTERMS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."ORDERS_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."ORDERS_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ORDERS_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SELLING_TYPE
--------------------------------------------------------

  ALTER TABLE "NTG"."SELLING_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SELLING_TYPE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SELLING_TYPE" MODIFY ("HIDE_IN_DROP_DOWN" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SELLING_TYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTRIBUTE_VALUE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_NTGL" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_NTGL" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_NTGL" MODIFY ("ATTRIBUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_NTGL" ADD PRIMARY KEY ("ATTRIBUTE_ID", "ORDER_ID", "SERVICE_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_TABLE
--------------------------------------------------------

  ALTER TABLE "NTG"."USER_TABLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."USER_TABLE" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "NTG"."USER_TABLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_CATEGORY
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_CATEGORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICE_CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PC_DELIVERY_TYPE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."PC_DELIVERY_TYPE_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."PC_DELIVERY_TYPE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."PC_DELIVERY_TYPE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEEDISCOUNT
--------------------------------------------------------

  ALTER TABLE "NTG"."EMPLOYEEDISCOUNT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."EMPLOYEEDISCOUNT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISCOUNT_CATEGORY_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."DISCOUNT_CATEGORY_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."DISCOUNT_CATEGORY_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."DISCOUNT_CATEGORY_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPONENT
--------------------------------------------------------

  ALTER TABLE "NTG"."COMPONENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."COMPONENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTRIBUTE_VALUE
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_VALUE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE" MODIFY ("ATTRIBUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE" ADD CONSTRAINT "ATTRIBUTE_VALUE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEEDISCOUNT_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."EMPLOYEEDISCOUNT_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."EMPLOYEEDISCOUNT_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."EMPLOYEEDISCOUNT_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPONENT_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."COMPONENT_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."COMPONENT_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."COMPONENT_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRICE_BASIS_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."PRICE_BASIS_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."PRICE_BASIS_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."PRICE_BASIS_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICETYPE
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICETYPE" ADD CONSTRAINT "SERVICETYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICETYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTRIBUTE_VALUE_LIST
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_LIST" ADD CONSTRAINT "SYS_C0011621" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_LIST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTRIBUTE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."ATTRIBUTE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICETYPE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICETYPE_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICETYPE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICETYPE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOWNLOAD_TYPE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."DOWNLOAD_TYPE_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."DOWNLOAD_TYPE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."DOWNLOAD_TYPE_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST3
--------------------------------------------------------

  ALTER TABLE "NTG"."TEST3" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."TEST3" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_BUNDLE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_BUNDLE_NTGL" ADD PRIMARY KEY ("REV", "COMP_ID", "SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICE_BUNDLE_NTGL" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICE_BUNDLE_NTGL" MODIFY ("COMP_ID" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICE_BUNDLE_NTGL" MODIFY ("REV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTRIBUTE_VALUE_LIST_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_LIST_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_LIST_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_LIST_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANCELATION_REASON_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."CANCELATION_REASON_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."CANCELATION_REASON_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."CANCELATION_REASON_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICEMIGRATION_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICEMIGRATION_NTGL" ADD PRIMARY KEY ("ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NTG"."SERVICEMIGRATION_NTGL" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "NTG"."SERVICEMIGRATION_NTGL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTRIBUTE
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE" ADD CONSTRAINT "FKBRS3RVERXJO5EU3AQ4A7LJ72X" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "NTG"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTRIBUTE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_NTGL" ADD CONSTRAINT "FK_18JIOTS38LP7HN9CBHJ52T01P" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTRIBUTE_VALUE
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_VALUE" ADD CONSTRAINT "FKCMU4MC8EBW9JRLJD8W358LE0M" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "NTG"."ORDERS" ("ID") ENABLE;
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE" ADD CONSTRAINT "FKDDWQWO5XTSHH4NRWTYTUG5NA7" FOREIGN KEY ("ATTRIBUTE_ID")
	  REFERENCES "NTG"."ATTRIBUTE" ("ID") ENABLE;
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE" ADD CONSTRAINT "FKH4BFFQHL8YI7WUX8CU0WTJRPW" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "NTG"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTRIBUTE_VALUE_LIST
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_LIST" ADD CONSTRAINT "ATTRIBUTE_VALUE_LIST_FK1" FOREIGN KEY ("SERVICEID")
	  REFERENCES "NTG"."SERVICE" ("ID") ENABLE;
  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_LIST" ADD CONSTRAINT "ATTRIBUTE_VALUE_LIST_FK2" FOREIGN KEY ("ATTRIBUTE_ID")
	  REFERENCES "NTG"."ATTRIBUTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTRIBUTE_VALUE_LIST_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_LIST_NTGL" ADD CONSTRAINT "FK_KP20XC5H2YF0KW0WTDXCDT0O7" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTRIBUTE_VALUE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."ATTRIBUTE_VALUE_NTGL" ADD CONSTRAINT "FK_SVMIX1QTVGWDHFWOWDMLRYTDA" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANDWIDTH_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."BANDWIDTH_NTGL" ADD CONSTRAINT "FK_3JYSXYBFMC35C6UARVIDXCT26" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CANCELATION_REASON_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."CANCELATION_REASON_NTGL" ADD CONSTRAINT "FK_8BTLNXGX21FBOIYSJEI9QQSVB" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "NTG"."CATEGORY" ADD CONSTRAINT "FK8HJC9174UNH2BMTPOGC3WWIMG" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "NTG"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORY_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."CATEGORY_NTGL" ADD CONSTRAINT "FK_JCSAGFNICHH7VIFY6E0OWC8Y0" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPONENT
--------------------------------------------------------

  ALTER TABLE "NTG"."COMPONENT" ADD CONSTRAINT "FK_O0BG21783L4L78F429H5QL4P4" FOREIGN KEY ("CATEGORYID_ID")
	  REFERENCES "NTG"."CATEGORY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPONENT_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."COMPONENT_NTGL" ADD CONSTRAINT "FK_4N0WWYWM5KQ0RU5FMEKW6BQ5Q" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRACTTERMS_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."CONTRACTTERMS_NTGL" ADD CONSTRAINT "FK_QJSM0S5UL6AFXAYBULA3NC505" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISCOUNT_CATEGORY_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."DISCOUNT_CATEGORY_NTGL" ADD CONSTRAINT "FK_15570KW319BMBP7036QNIXDCS" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOWNLOAD_TYPE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."DOWNLOAD_TYPE_NTGL" ADD CONSTRAINT "FK_5AJKSDH8V4JFWY68CLXER8TOT" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEEDISCOUNT_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."EMPLOYEEDISCOUNT_NTGL" ADD CONSTRAINT "FK_MLRGKBXCHYOGBCBVU79JR1SWK" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODIFYREASON_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."MODIFYREASON_NTGL" ADD CONSTRAINT "FK_K852RUOWO9JQA33WV1QT0UEG7" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "NTG"."ORDERS" ADD CONSTRAINT "FK_DTCE2FO4LT7NDB3OAFJJRFEU4" FOREIGN KEY ("SERVICEID")
	  REFERENCES "NTG"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."ORDERS_NTGL" ADD CONSTRAINT "FK_BSRYAUX5AAT4GGRG6PI2EA4Y7" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PC_DELIVERY_TYPE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."PC_DELIVERY_TYPE_NTGL" ADD CONSTRAINT "FK_MPBCWX0V0DXLUJNU11OLC101T" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRICE_BASIS_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."PRICE_BASIS_NTGL" ADD CONSTRAINT "FK_DBY7PCPYXBFHMB2JUIPA9EOJJ" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELLING_TYPE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SELLING_TYPE_NTGL" ADD CONSTRAINT "FK_BYGWVEBQLCPPAX1LWW1GJPIE" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICEMIGRATION_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICEMIGRATION_NTGL" ADD CONSTRAINT "FK_2LXJOXBRND7J1C82FVX3HLADE" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICETYPE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICETYPE_NTGL" ADD CONSTRAINT "FK_PP515E4HE96R6WDSHNKPKA107" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_BUNDLE
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_BUNDLE" ADD CONSTRAINT "FKBXMWAIRLRQASUI664YMLOJ65L" FOREIGN KEY ("COMP_ID")
	  REFERENCES "NTG"."COMPONENT" ("ID") ENABLE;
  ALTER TABLE "NTG"."SERVICE_BUNDLE" ADD CONSTRAINT "FKP0ENNIPAKBYMN5I33E5J31L2J" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "NTG"."SERVICE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_BUNDLE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_BUNDLE_NTGL" ADD CONSTRAINT "FK_3RKHCOM5YEGIT2PI942BBFER6" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_CATEGORY_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_CATEGORY_NTGL" ADD CONSTRAINT "FK_LXK7LYMQFY9SDHIARTFFUFELY" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."SERVICE_NTGL" ADD CONSTRAINT "FK_IYCWDP568GJBSH14WLH664ONF" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERTABLE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."USERTABLE_NTGL" ADD CONSTRAINT "FK_AFPQUBD9RA9XWTHWI3XT97PFN" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_TABLE_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."USER_TABLE_NTGL" ADD CONSTRAINT "FK_CTKOF1NXTW8557646SC7EWGLM" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VO_SUBSCRIBER_NTGL
--------------------------------------------------------

  ALTER TABLE "NTG"."VO_SUBSCRIBER_NTGL" ADD CONSTRAINT "FKM8CQCG89FYVSVUV13KPXWM3WV" FOREIGN KEY ("REV")
	  REFERENCES "NTG"."REVINFO" ("REV") ENABLE;
